[config]
schemaVersion = "0.0.1"

[package]
namespace = "DankTrain"
name = "Decagram"
versionNumber = "0.1.0"
description = "New Cards and Rebalance"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.5.7"
Conductor-Conductor = "0.2.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


